baseURL = 'https://jakeymg.github.io/'
languageCode = 'en-us'
title = 'JakeyMG'
theme = 'hugo-theme-console'

[params]
  description = 'Updated site description please'
  animateStyle = 'animate-fade-up' # Animation style for content

[[params.navlinks]]
  name = 'About'
  url = "/about/"

[[params.navlinks]]
  name = 'Posts'
  url = '/posts/'

[[params.navlinks]]
  name = 'Photos'
  url = '/photos/'