baseURL = 'https://jakeymg.github.io/'
languageCode = 'en-us'
title = 'JakeyMG'
theme = 'hugo-theme-console'

[params]
  description = 'JakeyMG Website and Portfolio'
  animateStyle = 'animate-fade-up' # Animation style for content

  [[params.navlinks]]
    name = 'about'
    url = "/about/"

  [[params.navlinks]]
    name = 'posts'
    url = '/posts/'

  [[params.navlinks]]
    name = 'images'
    url = '/images/'
  
  [[params.navlinks]]
    name = 'itch.io'
    url = 'https://jakey-mg.itch.io/'

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true